DROP TABLE IF EXISTS ligne_commande;
DROP TABLE IF EXISTS commande;
DROP TABLE IF EXISTS produit;
DROP TABLE IF EXISTS Client;


CREATE TABLE client (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    ville VARCHAR(100) NOT NULL,
    date_inscription DATE NOT NULL
);

CREATE TABLE produit (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    categorie VARCHAR(100) NOT NULL,
    prix NUMERIC (10,2) NOT NULL check (prix >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0)
);


CREATE TABLE commande (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES client(id) ON DELETE RESTRICT,
    date_commande DATE NOT NULL,
    statut VARCHAR(20) NOT NULL CHECK (statut IN ('payée', 'expédiée', 'livrée', 'annulée'))

);

CREATE TABLE ligne_commande (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id INTEGER NOT NULL REFERENCES commande(id) ON DELETE CASCADE,
    produit_id INTEGER NOT NULL REFERENCES produit(id) ON DELETE RESTRICT,
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC (10,2) NOT NULL CHECK (prix_unitaire >= 0)
);
